import { useState } from "react";
import { Download, Eye, Images, Loader2, Users } from "lucide-react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import PlannerLayout from "./PlannerLayout";
import { useQueryWrapper } from "@/api-hooks/react-query-wrapper";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
type EventRow={_id:string;title:string}; type Album={_id:string;title:string}; type Member={role:string;status:string;userId?:{_id:string;name?:string;email?:string}};
type Popular={imageId:string;views:number;downloads:number;shares:number;score:number;image?:{imageUrl?:string;albumId?:{title?:string};userTakenBy?:{name?:string}}};
type Summary={engagement:Record<string,number>;photos:{captured:number;published:number};daily:Array<{date:string;count:number}>;photographers:Array<{_id:string;count:number;name?:string}>;retouch:{statuses:Record<string,number>;averageTurnaroundMinutes:number};store:{revenue:number;paidOrders:number;purchasedPhotos:number;statuses:Record<string,number>};ai:Record<string,number>;guests:{activePersonalGalleries:number;notifications:Record<string,number>};transfers:Record<string,number>;popularPhotos:Popular[]};
export default function AnalyticsDashboard(){
  const eventsQ=useQueryWrapper<{data:EventRow[]}>(["analytics-events"],"/event/my-events?page=1&limit=100",{withToken:true,withCredentials:true}); const events=eventsQ.data?.data||[];
  const [eventId,setEventId]=useState(""); const selected=eventId||events[0]?._id||""; const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [albumId,setAlbumId]=useState("all"); const [photographerId,setPhotographerId]=useState("all"); const [channel,setChannel]=useState("all");
  const albumsQ=useQueryWrapper<{data:Album[]}>(["analytics-albums",selected],selected?`/album/get-all?eventId=${selected}`:"/album/get-all",{withToken:true,withCredentials:true,enabled:Boolean(selected)});
  const teamQ=useQueryWrapper<{data:Member[]}>(["analytics-team",selected],selected?`/event-members?eventId=${selected}`:"/event-members",{withToken:true,withCredentials:true,enabled:Boolean(selected)});
  const qs=new URLSearchParams(); if(selected)qs.set("eventId",selected); if(from)qs.set("from",new Date(`${from}T00:00:00`).toISOString()); if(to)qs.set("to",new Date(`${to}T23:59:59`).toISOString()); if(albumId!=="all")qs.set("albumId",albumId); if(photographerId!=="all")qs.set("photographerId",photographerId); if(channel!=="all")qs.set("channel",channel);
  const summaryQ=useQueryWrapper<Summary>(["analytics-summary",selected,from,to,albumId,photographerId,channel],selected?`/analytics/summary?${qs.toString()}`:"/analytics/summary",{withToken:true,withCredentials:true,enabled:Boolean(selected),refetchInterval:15000}); const s=summaryQ.data;
  const photographers=(teamQ.data?.data||[]).filter(row=>["photographer","assistant_photographer"].includes(row.role)&&row.status==="active"&&row.userId);
  return <PlannerLayout><div className="space-y-5">
    <div><p className="text-sm font-medium text-muted-foreground">Phase 3 intelligence</p><h1 className="text-2xl font-bold">Analytics</h1><p className="mt-1 text-sm text-muted-foreground">Engagement, photo delivery, photographer, retouch, AI and sales performance.</p></div>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-6"><Filter label="Event"><Select value={selected} onValueChange={v=>{setEventId(v);setAlbumId("all");setPhotographerId("all")}}><SelectTrigger><SelectValue placeholder="Event"/></SelectTrigger><SelectContent>{events.map(e=><SelectItem key={e._id} value={e._id}>{e.title}</SelectItem>)}</SelectContent></Select></Filter><Filter label="From"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Filter><Filter label="To"><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Filter><Filter label="Category"><Select value={albumId} onValueChange={setAlbumId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All</SelectItem>{(albumsQ.data?.data||[]).map(a=><SelectItem key={a._id} value={a._id}>{a.title}</SelectItem>)}</SelectContent></Select></Filter><Filter label="Photographer"><Select value={photographerId} onValueChange={setPhotographerId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All</SelectItem>{photographers.map(row=><SelectItem key={row.userId!._id} value={row.userId!._id}>{row.userId?.name||row.userId?.email}</SelectItem>)}</SelectContent></Select></Filter><Filter label="Channel"><Select value={channel} onValueChange={setChannel}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All</SelectItem><SelectItem value="live_gallery">Live gallery</SelectItem><SelectItem value="personal_gallery">Personal gallery</SelectItem><SelectItem value="store">Store</SelectItem></SelectContent></Select></Filter></CardContent></Card>
    {summaryQ.isLoading?<div className="flex h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin"/></div>:s?<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Eye} label="Gallery visits" value={Number(s.engagement.gallery_visit||0)}/><Metric icon={Users} label="Unique viewers" value={Number(s.engagement.uniqueViewers||0)}/><Metric icon={Images} label="Photo views" value={Number(s.engagement.image_view||0)}/><Metric icon={Download} label="Downloads" value={Number(s.engagement.download||0)}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Engagement over time</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={s.daily}><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="count" stroke="currentColor" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>Photo pipeline</CardTitle></CardHeader><CardContent className="space-y-3"><Row label="Captured" value={s.photos.captured}/><Row label="Published" value={s.photos.published}/>{Object.entries(s.transfers||{}).map(([k,v])=><Row key={k} label={`Transfer ${k}`} value={v}/>)}</CardContent></Card><Card><CardHeader><CardTitle>Retouch production</CardTitle></CardHeader><CardContent className="space-y-3"><Row label="Average turnaround" value={`${s.retouch.averageTurnaroundMinutes} min`}/>{Object.entries(s.retouch.statuses||{}).map(([k,v])=><Row key={k} label={k.replace(/_/g," ")} value={v}/>)}</CardContent></Card><Card><CardHeader><CardTitle>Store & AI</CardTitle></CardHeader><CardContent className="space-y-3"><Row label="Revenue" value={s.store.revenue.toFixed(2)}/><Row label="Paid orders" value={s.store.paidOrders}/><Row label="Purchased photos" value={s.store.purchasedPhotos}/>{Object.entries(s.ai||{}).map(([k,v])=><Row key={k} label={`AI ${k}`} value={v}/>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Popular photos</CardTitle></CardHeader><CardContent>{(s.popularPhotos||[]).length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{s.popularPhotos.map(photo=><div key={photo.imageId} className="overflow-hidden rounded-xl border">{photo.image?.imageUrl?<img src={photo.image.imageUrl} className="aspect-[4/3] w-full object-cover"/>:null}<div className="space-y-1 p-3"><p className="truncate text-sm font-medium">{photo.image?.userTakenBy?.name||"Photo"}</p><div className="flex flex-wrap gap-1"><Badge variant="outline">{photo.views} views</Badge><Badge variant="outline">{photo.downloads} downloads</Badge><Badge variant="outline">{photo.shares} shares</Badge></div></div></div>)}</div>:<p className="text-sm text-muted-foreground">No photo engagement yet.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Photographer activity</CardTitle></CardHeader><CardContent>{s.photographers.length?<div className="space-y-2">{s.photographers.map((p,index)=><div key={p._id} className="flex items-center justify-between rounded-xl border p-3"><div className="flex items-center gap-3"><Badge variant="outline">#{index+1}</Badge><span className="font-medium">{p.name||"Photographer"}</span></div><span className="font-semibold">{p.count} uploads</span></div>)}</div>:<p className="text-sm text-muted-foreground">No photographer activity yet.</p>}</CardContent></Card></>:<div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">Select an event to view analytics.</div>}
  </div></PlannerLayout>
}
function Filter({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1"><Label>{label}</Label>{children}</div>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:number}){return <Card><CardContent className="flex items-center gap-3 p-4"><Icon className="h-5 w-5"/><div><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
function Row({label,value}:{label:string;value:string|number}){return <div className="flex items-center justify-between border-b pb-2 text-sm last:border-0"><span className="capitalize text-muted-foreground">{label}</span><span className="font-semibold">{value}</span></div>}
