name: mobileapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  animations: ^2.1.1
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  logger: ^2.6.2
  url_launcher: ^6.3.2
  intl: ^0.20.2
  auto_route: ^11.1.0
  get_it: ^9.2.1
  dartz: ^0.10.1
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  cached_query: ^3.5.1
  cached_query_flutter: ^3.3.6
  cached_storage: ^3.2.6
  flutter_stripe: ^12.4.0
  image_picker: ^1.2.0
  dotted_border: ^3.1.0
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  share_plus: ^12.0.2
  font_awesome_flutter: ^10.8.0
  signals: ^6.3.0
  onesignal_flutter: ^5.5.3
  flutter_dotenv: ^6.0.1
  package_info_plus: ^9.0.1
  camera: ^0.12.0+1
  multicast_dns: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  flutter_launcher_icons: ^0.14.4
  auto_route_generator: ^10.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.jpeg
    - assets/icon-logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon-logo.jpg
  adaptive_icon_background: "#FF9A2F"
  adaptive_icon_foreground: assets/icon-logo.jpg
