import { useEffect, useMemo, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Check, Download, Eye, Loader2, RefreshCw, Scissors, Upload, UserRoundCheck, X } from "lucide-react";
import { toast } from "sonner";
import { GetRequestAxios, PatchRequestAxios, PostRequestAxios } from "@/api-hooks/api-hooks";
import { useQueryWrapper } from "@/api-hooks/react-query-wrapper";
import { useWorkspaceAccess } from "@/hooks/use-workspace-access";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import RetouchLayout from "./RetouchLayout";

type EventRow={_id:string;title:string};
type Membership={role:string;status:string;eventId:EventRow|string};
type Job={_id:string;status:string;originalImageUrl:string;currentImageUrl:string;retouchedImageUrl?:string;internalNote?:string;rejectionReason?:string;albumId?:{_id:string;title?:string};photographerId?:{_id:string;name?:string};assignedRetoucherId?:{_id:string;name?:string};desktopDeviceId?:string;desktopLastSeenAt?:string;createdAt?:string};
type JobsResponse={data:Job[];totalItems:number;summary:Record<string,number>};
type TeamMember={_id:string;role:string;status:string;userId?:{_id:string;name?:string;email?:string}};
type Album={_id:string;title:string};
type Settings={bypassReviewer?:boolean;autoPublishApproved?:boolean;desktopDownloadConcurrency?:number};
type DesktopClient={deviceId:string;retoucherId?:string;lastSeenAt?:string;online:boolean;totalJobs:number;downloaded:number;retouching:number;readyForReview:number;published:number};
const statuses=["all","incoming","assigned","downloaded","retouching","ready_for_review","approved","rejected","published","failed"];
const baseUrl=import.meta.env.VITE_BASE_URL??"";

export default function RetouchConsole(){
  const queryClient=useQueryClient(); const access=useWorkspaceAccess();
  const owned=useQueryWrapper<{data:EventRow[]}>(["retouch-owned-events"],"/event/my-events?page=1&limit=100",{withToken:true,withCredentials:true});
  const mine=useQueryWrapper<{data:Membership[]}>(["retouch-memberships"],"/event-members/mine",{withToken:true,withCredentials:true});
  const events=useMemo(()=>{const map=new Map<string,EventRow>(); for(const row of owned.data?.data||[]) map.set(row._id,row); for(const membership of mine.data?.data||[]){ if(membership.status!=="active") continue; const event=membership.eventId; if(typeof event==="object"&&event?._id) map.set(event._id,event); } return [...map.values()];},[owned.data?.data,mine.data?.data]);
  const [eventId,setEventId]=useState(""); const selectedEventId=eventId||events[0]?._id||""; const [status,setStatus]=useState("all"); const [selected,setSelected]=useState<Set<string>>(new Set()); const [retoucherId,setRetoucherId]=useState(""); const [compare,setCompare]=useState<Job|null>(null); const [albumId,setAlbumId]=useState("all"); const [photographerId,setPhotographerId]=useState("all"); const [from,setFrom]=useState(""); const [to,setTo]=useState("");
  const jobParams=new URLSearchParams({eventId:selectedEventId,limit:"500"}); if(status!=="all")jobParams.set("status",status); if(albumId!=="all")jobParams.set("albumId",albumId); if(photographerId!=="all")jobParams.set("photographerId",photographerId); if(from)jobParams.set("from",new Date(`${from}T00:00:00`).toISOString()); if(to)jobParams.set("to",new Date(`${to}T23:59:59`).toISOString());
  const jobs=useQueryWrapper<JobsResponse>(["retouch-jobs",selectedEventId,status,albumId,photographerId,from,to],selectedEventId?`/retouch/jobs?${jobParams.toString()}`:"/retouch/jobs?eventId=000000000000000000000000",{withToken:true,withCredentials:true,enabled:Boolean(selectedEventId),refetchInterval:3000});
  const team=useQueryWrapper<{data:TeamMember[]}>(["retouch-team",selectedEventId],selectedEventId?`/event-members?eventId=${selectedEventId}`:"/event-members",{withToken:true,withCredentials:true,enabled:Boolean(selectedEventId&&access.data?.planner)});
  const albums=useQueryWrapper<{data:Album[]}>(["retouch-albums",selectedEventId],selectedEventId?`/album/get-all?eventId=${selectedEventId}`:"/album/get-all",{withToken:true,withCredentials:true,enabled:Boolean(selectedEventId)});
  const settings=useQueryWrapper<{data:Settings}>(["retouch-settings",selectedEventId],selectedEventId?`/retouch/settings?eventId=${selectedEventId}`:"/retouch/settings",{withToken:true,withCredentials:true,enabled:Boolean(selectedEventId&&access.data?.planner)});
  const desktops=useQueryWrapper<{data:DesktopClient[];online:number}>(["retouch-desktop-status",selectedEventId],selectedEventId?`/retouch/desktop-status?eventId=${selectedEventId}`:"/retouch/desktop-status",{withToken:true,withCredentials:true,enabled:Boolean(selectedEventId&&access.data?.planner),refetchInterval:5000});
  useEffect(()=>{
    if(!selectedEventId)return;
    const source=new EventSource(`${baseUrl}/retouch/stream?eventId=${encodeURIComponent(selectedEventId)}`,{withCredentials:true});
    const sync=()=>{
      queryClient.invalidateQueries({queryKey:["retouch-jobs"]});
      queryClient.invalidateQueries({queryKey:["retouch-desktop-status"]});
    };
    source.addEventListener("retouch",sync);
    return()=>source.close();
  },[selectedEventId,queryClient]);
  const retouchers=(team.data?.data||[]).filter(row=>row.role==="retoucher"&&row.status==="active"&&row.userId);
  const photographers=(team.data?.data||[]).filter(row=>["photographer","assistant_photographer"].includes(row.role)&&row.status==="active"&&row.userId);
  const refresh=()=>{queryClient.invalidateQueries({queryKey:["retouch-jobs"]});queryClient.invalidateQueries({queryKey:["retouch-settings"]});};
  const assign=useMutation({mutationFn:async()=>{if(!retoucherId||!selected.size)throw new Error("Select jobs and a retoucher");const [r,e]=await PostRequestAxios("/retouch/assign",{eventId:selectedEventId,jobIds:[...selected],retoucherId},{withToken:true,withCredentials:true});if(e||!r)throw new Error(e?.message||"Assignment failed");return r;},onSuccess:()=>{toast.success("Retouch jobs assigned");setSelected(new Set());refresh();},onError:(e:Error)=>toast.error(e.message)});
  const unassign=useMutation({mutationFn:async()=>{if(!selected.size)throw new Error("Select jobs first");const [r,e]=await PostRequestAxios("/retouch/unassign",{eventId:selectedEventId,jobIds:[...selected]},{withToken:true,withCredentials:true});if(e||!r)throw new Error(e?.message||"Unassign failed");return r;},onSuccess:()=>{toast.success("Jobs returned to incoming");setSelected(new Set());refresh();},onError:(e:Error)=>toast.error(e.message)});
  const setJobStatus=useMutation({mutationFn:async({jobId,next}:{jobId:string;next:string})=>{const [r,e]=await PatchRequestAxios("/retouch/status",{jobId,status:next},{withToken:true,withCredentials:true});if(e||!r)throw new Error(e?.message||"Status update failed");return r;},onSuccess:refresh,onError:(e:Error)=>toast.error(e.message)});
  const review=useMutation({mutationFn:async({jobId,decision}:{jobId:string;decision:"approve"|"reject"})=>{const [r,e]=await PatchRequestAxios("/retouch/review",{jobId,decision,publish:true},{withToken:true,withCredentials:true});if(e||!r)throw new Error(e?.message||"Review failed");return r;},onSuccess:(_,vars)=>{toast.success(vars.decision==="approve"?"Retouch approved and delivered":"Retouch returned for changes");refresh();},onError:(e:Error)=>toast.error(e.message)});
  const uploadVersion=async(job:Job,file:File)=>{try{const form=new FormData();form.append("file",file);const [uploaded,error]=await PostRequestAxios<{url?:string}>("/image/upload",form,{withToken:true,withCredentials:true,headers:{"Content-Type":"multipart/form-data"}});if(error||!uploaded?.url)throw new Error(error?.message||"Upload failed");const [result,versionError]=await PostRequestAxios("/retouch/version",{jobId:job._id,imageUrl:uploaded.url},{withToken:true,withCredentials:true});if(versionError||!result)throw new Error(versionError?.message||"Could not save retouched version");toast.success("Retouched file uploaded for review");refresh();}catch(error){toast.error(error instanceof Error?error.message:"Upload failed")}};
  const saveSettings=useMutation({mutationFn:async(next:Settings)=>{const [r,e]=await PatchRequestAxios("/retouch/settings",{eventId:selectedEventId,...next},{withToken:true,withCredentials:true});if(e||!r)throw new Error(e?.message||"Could not save workflow");return r;},onSuccess:()=>{toast.success("Retouch workflow updated");refresh();},onError:(e:Error)=>toast.error(e.message)});
  const bulkReview=useMutation({mutationFn:async(decision:"approve"|"reject")=>{if(!selected.size)throw new Error("Select review jobs first");const [r,e]=await PatchRequestAxios("/retouch/review-batch",{jobIds:[...selected],decision,publish:true},{withToken:true,withCredentials:true});if(e||!r)throw new Error(e?.message||"Bulk review failed");return r;},onSuccess:(_,decision)=>{toast.success(decision==="approve"?"Selected retouches approved":"Selected retouches rejected");setSelected(new Set());refresh();},onError:(e:Error)=>toast.error(e.message)});
  const rows=jobs.data?.data||[]; const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});
  return <RetouchLayout><div className="space-y-5">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Phase 3 production</p><h1 className="text-2xl font-bold">Retouch & Review Console</h1><p className="mt-1 text-sm text-muted-foreground">Incoming → download → retouch → review → publish.</p></div><div className="grid gap-2 sm:grid-cols-2"><div><Label>Event</Label><Select value={selectedEventId} onValueChange={v=>{setEventId(v);setSelected(new Set())}}><SelectTrigger className="w-64"><SelectValue placeholder="Choose event"/></SelectTrigger><SelectContent>{events.map(event=><SelectItem key={event._id} value={event._id}>{event.title}</SelectItem>)}</SelectContent></Select></div><div><Label>Status</Label><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-52"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(value=><SelectItem key={value} value={value}>{value.replace(/_/g," ")}</SelectItem>)}</SelectContent></Select></div></div></div>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4"><div><Label>Category filter</Label><Select value={albumId} onValueChange={setAlbumId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{(albums.data?.data||[]).map(album=><SelectItem key={album._id} value={album._id}>{album.title}</SelectItem>)}</SelectContent></Select></div>{access.data?.planner?<div><Label>Photographer</Label><Select value={photographerId} onValueChange={setPhotographerId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All photographers</SelectItem>{photographers.map(row=><SelectItem key={row.userId!._id} value={row.userId!._id}>{row.userId?.name||row.userId?.email}</SelectItem>)}</SelectContent></Select></div>:<div/>}<div><Label>From</Label><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><Label>To</Label><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(jobs.data?.summary||{}).map(([key,value])=><Card key={key}><CardContent className="p-4"><p className="text-2xl font-bold">{value}</p><p className="text-xs capitalize text-muted-foreground">{key.replace(/_/g," ")}</p></CardContent></Card>)}</div>
    {access.data?.planner?<Card><CardContent className="flex flex-col gap-3 p-4 lg:flex-row lg:items-end"><div className="flex-1"><Label>Assign selected to retoucher</Label><Select value={retoucherId} onValueChange={setRetoucherId}><SelectTrigger><SelectValue placeholder="Select retoucher"/></SelectTrigger><SelectContent>{retouchers.map(row=><SelectItem key={row.userId!._id} value={row.userId!._id}>{row.userId?.name||row.userId?.email}</SelectItem>)}</SelectContent></Select></div><Badge variant="secondary">{selected.size} selected</Badge><Button disabled={!selected.size||!retoucherId||assign.isPending} onClick={()=>assign.mutate()}><UserRoundCheck className="mr-2 h-4 w-4"/>Assign</Button><Button variant="outline" disabled={!selected.size||unassign.isPending} onClick={()=>unassign.mutate()}><RefreshCw className="mr-2 h-4 w-4"/>Unassign</Button></CardContent></Card>:null}
    {access.data?.reviewer?<Card><CardContent className="flex flex-wrap items-center gap-2 p-4"><Badge variant="secondary">{selected.size} selected</Badge><Button size="sm" disabled={!selected.size||bulkReview.isPending} onClick={()=>bulkReview.mutate("approve")}><Check className="mr-2 h-4 w-4"/>Bulk approve & publish</Button><Button size="sm" variant="destructive" disabled={!selected.size||bulkReview.isPending} onClick={()=>bulkReview.mutate("reject")}><X className="mr-2 h-4 w-4"/>Bulk reject</Button></CardContent></Card>:null}
    {access.data?.planner&&settings.data?.data?<Card><CardHeader><CardTitle className="text-base">Workflow controls</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><SettingToggle label="Bypass reviewer for trusted event" checked={Boolean(settings.data.data.bypassReviewer)} onChange={value=>saveSettings.mutate({bypassReviewer:value})}/><SettingToggle label="Auto-publish approved retouches" checked={settings.data.data.autoPublishApproved!==false} onChange={value=>saveSettings.mutate({autoPublishApproved:value})}/><div><Label>Desktop download concurrency</Label><Input type="number" min={1} max={12} defaultValue={settings.data.data.desktopDownloadConcurrency||3} onBlur={e=>saveSettings.mutate({desktopDownloadConcurrency:Number(e.target.value)||3})}/></div></CardContent></Card>:null}
    {access.data?.planner?<Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-base">Desktop sync clients</CardTitle><Badge variant="outline">{desktops.data?.online||0} online</Badge></div></CardHeader><CardContent>{(desktops.data?.data||[]).length===0?<p className="text-sm text-muted-foreground">No desktop retoucher has connected yet.</p>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(desktops.data?.data||[]).map(client=>{const member=retouchers.find(row=>row.userId?._id===client.retoucherId);return <div key={`${client.deviceId}-${client.retoucherId||"none"}`} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><p className="truncate font-medium">{member?.userId?.name||member?.userId?.email||"Retoucher desktop"}</p><Badge variant={client.online?"default":"secondary"}>{client.online?"online":"offline"}</Badge></div><p className="mt-1 truncate font-mono text-xs text-muted-foreground">{client.deviceId}</p><p className="mt-2 text-xs text-muted-foreground">{client.retouching} retouching · {client.readyForReview} ready · {client.published} published · {client.totalJobs} synced</p><p className="mt-1 text-[11px] text-muted-foreground">Last seen {client.lastSeenAt?new Date(client.lastSeenAt).toLocaleTimeString():"unknown"}</p></div>})}</div>}</CardContent></Card>:null}
    <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Production queue</CardTitle><Button variant="outline" size="sm" onClick={refresh}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div></CardHeader><CardContent>{jobs.isLoading?<div className="flex h-48 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin"/></div>:rows.length===0?<div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No retouch jobs in this filter.</div>:<div className="space-y-3">{rows.map(job=><div key={job._id} className="grid gap-3 rounded-xl border p-3 lg:grid-cols-[auto_112px_minmax(0,1fr)_auto] lg:items-center"><Checkbox checked={selected.has(job._id)} onCheckedChange={()=>toggle(job._id)}/><button className="relative overflow-hidden rounded-lg bg-muted" onClick={()=>setCompare(job)}><img src={job.currentImageUrl} className="aspect-[4/3] h-20 w-28 object-cover"/><Eye className="absolute bottom-1 right-1 h-4 w-4 rounded bg-background/80 p-0.5"/></button><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={job.status}/>{job.albumId?.title?<Badge variant="outline">{job.albumId.title}</Badge>:null}{job.assignedRetoucherId?.name?<Badge variant="secondary">{job.assignedRetoucherId.name}</Badge>:null}</div><p className="mt-1 truncate text-xs text-muted-foreground">Photographer: {job.photographerId?.name||"Unknown"}{job.desktopDeviceId?` · Desktop ${job.desktopDeviceId}`:""}</p>{job.rejectionReason?<p className="mt-1 text-xs text-destructive">{job.rejectionReason}</p>:null}</div><div className="flex flex-wrap justify-end gap-2">{job.status==="assigned"?<Button size="sm" variant="outline" onClick={()=>setJobStatus.mutate({jobId:job._id,next:"downloaded"})}><Download className="mr-1 h-3.5 w-3.5"/>Downloaded</Button>:null}{["assigned","downloaded","rejected","failed"].includes(job.status)?<Button size="sm" variant="outline" onClick={()=>setJobStatus.mutate({jobId:job._id,next:"retouching"})}><Scissors className="mr-1 h-3.5 w-3.5"/>Start</Button>:null}{["assigned","downloaded","retouching","rejected","failed"].includes(job.status)?<label className="inline-flex cursor-pointer items-center rounded-md bg-primary px-3 py-2 text-xs font-medium text-primary-foreground"><Upload className="mr-1 h-3.5 w-3.5"/>Upload edit<input type="file" accept="image/*" className="hidden" onChange={e=>{const file=e.target.files?.[0];e.currentTarget.value="";if(file)void uploadVersion(job,file)}}/></label>:null}{job.status==="ready_for_review"&&access.data?.reviewer?<><Button size="sm" onClick={()=>review.mutate({jobId:job._id,decision:"approve"})}><Check className="mr-1 h-3.5 w-3.5"/>Approve</Button><Button size="sm" variant="destructive" onClick={()=>review.mutate({jobId:job._id,decision:"reject"})}><X className="mr-1 h-3.5 w-3.5"/>Reject</Button></>:null}</div></div>)}</div>}</CardContent></Card>
    {compare?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onClick={()=>setCompare(null)}><div className="w-full max-w-5xl rounded-2xl bg-background p-4" onClick={e=>e.stopPropagation()}><div className="mb-3 flex items-center justify-between"><p className="font-semibold">Original / current retouch</p><Button variant="ghost" onClick={()=>setCompare(null)}>Close</Button></div><div className="grid gap-3 md:grid-cols-2"><div><p className="mb-2 text-xs font-semibold text-muted-foreground">ORIGINAL</p><img src={compare.originalImageUrl} className="max-h-[70vh] w-full rounded-xl object-contain"/></div><div><p className="mb-2 text-xs font-semibold text-muted-foreground">CURRENT</p><img src={compare.currentImageUrl} className="max-h-[70vh] w-full rounded-xl object-contain"/></div></div></div></div>:null}
  </div></RetouchLayout>
}
function StatusBadge({status}:{status:string}){const destructive=["failed","rejected"].includes(status);return <Badge variant={destructive?"destructive":status==="published"?"default":"outline"}>{status.replace(/_/g," ")}</Badge>}
function SettingToggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <div className="flex items-center justify-between gap-3 rounded-xl border p-3"><span className="text-sm font-medium">{label}</span><Switch checked={checked} onCheckedChange={onChange}/></div>}
