import { useEffect, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { Download, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { GetRequestAxios, PostRequestAxios } from "@/api-hooks/api-hooks";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
type Order={orderNo:string;email:string;currency:string;amount:number;downloadExpiresAt?:string;eventId?:{_id?:string;title?:string};imageIds?:Array<{_id:string;previewUrl:string;downloadUrl:string}>};
const baseUrl=import.meta.env.VITE_BASE_URL??"";
export default function StoreOrder(){const {orderId=""}=useParams();const [params,setParams]=useSearchParams();const [token,setToken]=useState(params.get("token")||"");const [order,setOrder]=useState<Order>();const [loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;void(async()=>{let access=token;const session=params.get("session_id");if(!access&&session){const [verified,error]=await PostRequestAxios<{downloadToken?:string}>("/store/public/verify",{orderId,sessionId:session},{withCredentials:false,redirectOnUnauthorized:false});if(error||!verified?.downloadToken){if(!cancelled){setLoading(false);toast.error(error?.message||"Payment verification failed")}return;}access=verified.downloadToken;setToken(access);const next=new URLSearchParams();next.set("token",access);setParams(next,{replace:true});}if(!access){if(!cancelled)setLoading(false);return;}const [data,error]=await GetRequestAxios<{data:Order}>(`/store/public/order?orderId=${orderId}&token=${encodeURIComponent(access)}`,{withCredentials:false,redirectOnUnauthorized:false});if(!cancelled){setLoading(false);if(error||!data?.data)toast.error(error?.message||"Order link invalid");else setOrder(data.data);}})();return()=>{cancelled=true}},[orderId,params,setParams,token]);
 const download=async(url:string,name:string,imageId:string)=>{if(order?.eventId?._id)void PostRequestAxios("/analytics/track",{eventId:order.eventId._id,imageId,type:"download",channel:"store"},{withCredentials:false,redirectOnUnauthorized:false});try{const target=url.startsWith("http")?url:`${baseUrl}${url}`;const response=await fetch(target);const blob=await response.blob();const local=URL.createObjectURL(blob);const a=document.createElement("a");a.href=local;a.download=name;a.click();URL.revokeObjectURL(local)}catch{const target=url.startsWith("http")?url:`${baseUrl}${url}`;window.open(target,"_blank","noopener,noreferrer")}};
 if(loading)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin"/></div>;if(!order)return <div className="flex min-h-screen items-center justify-center p-6 text-center"><div><h1 className="text-2xl font-bold">Order access unavailable</h1><p className="mt-2 text-sm text-muted-foreground">Use the secure delivery link from your payment confirmation.</p></div></div>;
 return <main className="mx-auto min-h-screen max-w-6xl space-y-5 px-4 py-8 sm:px-6"><div><p className="text-sm text-muted-foreground">{order.orderNo}</p><h1 className="text-3xl font-bold">{order.eventId?.title||"Your purchased photos"}</h1><p className="mt-1 text-sm text-muted-foreground">Paid {order.currency} {Number(order.amount).toFixed(2)} · Download access expires {order.downloadExpiresAt?new Date(order.downloadExpiresAt).toLocaleString():"soon"}.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(order.imageIds||[]).map((image,index)=><Card key={image._id} className="overflow-hidden"><img src={`${baseUrl}${image.previewUrl}`} className="aspect-[4/3] w-full object-cover"/><CardContent className="p-3"><Button className="w-full" onClick={()=>void download(image.downloadUrl,`photo-${index+1}.jpg`,image._id)}><Download className="mr-2 h-4 w-4"/>Download original</Button></CardContent></Card>)}</div></main>}
