import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { Loader2, ShoppingCart } from "lucide-react";
import { toast } from "sonner";
import { GetRequestAxios, PostRequestAxios } from "@/api-hooks/api-hooks";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Catalog={event:{_id:string;title:string;description?:string;branding?:{logoUrl?:string;coverUrl?:string;primaryColor?:string}};settings:{currency:string;singlePhotoPrice:number;bundlePrice:number;bundleMinPhotos:number;termsText?:string};data:Array<{_id:string;previewUrl:string}>;totalItems:number};
const baseUrl=import.meta.env.VITE_BASE_URL??"";
export default function Storefront(){
 const {eventId=""}=useParams(); const [catalog,setCatalog]=useState<Catalog>(); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Set<string>>(new Set()); const [email,setEmail]=useState(""); const [whatsapp,setWhatsapp]=useState(""); const [checkout,setCheckout]=useState(false); const [checkoutKey,setCheckoutKey]=useState("");
 useEffect(()=>{let mounted=true; void (async()=>{const [data,error]=await GetRequestAxios<Catalog>(`/store/public/catalog?eventId=${eventId}`,{withCredentials:false,redirectOnUnauthorized:false}); if(!mounted)return; setLoading(false); if(error||!data){toast.error(error?.message||"Store unavailable");return;} setCatalog(data); void PostRequestAxios("/analytics/track",{eventId,type:"store_view",channel:"store"},{withCredentials:false,redirectOnUnauthorized:false});})(); return()=>{mounted=false}},[eventId]);
 useEffect(()=>setCheckoutKey(""),[eventId,email,whatsapp,selected]);
 const price=useMemo(()=>{if(!catalog)return 0; const count=selected.size; return catalog.settings.bundlePrice>0&&count>=catalog.settings.bundleMinPhotos?catalog.settings.bundlePrice:catalog.settings.singlePhotoPrice*count},[catalog,selected]);
 const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
 const startCheckout=async()=>{if(!catalog||!selected.size||!email.trim())return;const key=checkoutKey||crypto.randomUUID();if(!checkoutKey)setCheckoutKey(key);setCheckout(true);const [data,error]=await PostRequestAxios<{url?:string}>("/store/public/checkout",{eventId,imageIds:[...selected],email:email.trim(),whatsapp:whatsapp.trim()||undefined,idempotencyKey:key},{withCredentials:false,redirectOnUnauthorized:false});setCheckout(false);if(error||!data?.url){toast.error(error?.message||"Checkout failed");return;}void PostRequestAxios("/analytics/track",{eventId,type:"store_checkout",channel:"store"},{withCredentials:false,redirectOnUnauthorized:false});window.location.href=data.url;};
 if(loading)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin"/></div>; if(!catalog)return <div className="flex min-h-screen items-center justify-center p-6 text-center"><div><h1 className="text-2xl font-bold">Store unavailable</h1><p className="mt-2 text-sm text-muted-foreground">This event is not currently selling photos.</p></div></div>;
 const branding=catalog.event.branding||{}; return <div className="min-h-screen bg-muted/20"><header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3">{branding.logoUrl?<img src={branding.logoUrl} className="h-9 max-w-28 object-contain"/>:<span className="font-bold">airpix store</span>}<span className="hidden text-sm text-muted-foreground sm:inline">{catalog.event.title}</span></div><div className="flex items-center gap-2"><ShoppingCart className="h-4 w-4"/><span className="text-sm font-semibold">{selected.size}</span><span className="text-sm">{catalog.settings.currency} {price.toFixed(2)}</span></div></div></header>
 {branding.coverUrl?<div className="relative h-56 overflow-hidden"><img src={branding.coverUrl} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-black/45"/><div className="absolute inset-0 flex items-end"><div className="mx-auto w-full max-w-[1500px] px-4 pb-8 text-white sm:px-6"><h1 className="text-3xl font-bold">{catalog.event.title}</h1><p className="mt-1 text-white/80">Choose the photos you want to own.</p></div></div></div>:<div className="mx-auto max-w-[1500px] px-4 py-8 sm:px-6"><h1 className="text-3xl font-bold">{catalog.event.title}</h1><p className="mt-1 text-muted-foreground">Choose the photos you want to own.</p></div>}
 <main className="mx-auto max-w-[1500px] space-y-5 px-4 py-6 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{catalog.totalItems} available photos · {catalog.settings.currency} {catalog.settings.singlePhotoPrice.toFixed(2)} each{catalog.settings.bundlePrice>0?` · ${catalog.settings.bundleMinPhotos}+ photos ${catalog.settings.currency} ${catalog.settings.bundlePrice.toFixed(2)}`:""}</p><Button variant="outline" onClick={()=>setSelected(new Set(catalog.data.map(x=>x._id)))}>Select all</Button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{catalog.data.map(photo=><Card key={photo._id} className="overflow-hidden"><div className="relative aspect-[4/3] bg-muted"><img src={`${baseUrl}${photo.previewUrl}`} loading="lazy" className="h-full w-full object-cover"/><label className="absolute left-3 top-3 rounded-full bg-background/90 p-1.5 shadow"><Checkbox checked={selected.has(photo._id)} onCheckedChange={()=>toggle(photo._id)}/></label></div></Card>)}</div>
 {selected.size?<Card className="sticky bottom-4 border-primary/30 shadow-lg"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><div><Label>Email for delivery</Label><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div><div><Label>WhatsApp (optional)</Label><Input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} placeholder="+1..."/></div><Button disabled={checkout||!email.trim()} onClick={()=>void startCheckout()}>{checkout?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<ShoppingCart className="mr-2 h-4 w-4"/>}Pay {catalog.settings.currency} {price.toFixed(2)}</Button>{catalog.settings.termsText?<p className="text-xs text-muted-foreground md:col-span-3">{catalog.settings.termsText}</p>:null}</CardContent></Card>:null}</main></div>
}
